import { Driver } from './driver-model';

export const DRIVERS: Driver[] = [
  { id: 1,
     name: 'Babatunde Marvel',
      carType:'Toyota Camry', 
      plateNo: 'AA884BKN',
      vehicleType: 'car-alt',
       timeAway:30, 
       rating:4, 
       img_url:'assets/img/Assets/old-driver-2.jpg'  },
       { id: 2,
        name: 'Akindayo Marvel',
         carType:'Toyota Camry', 
         plateNo: 'BB884BKN',
         vehicleType: 'motorcycle',
          timeAway:30, 
          rating:4, 
          img_url:'assets/img/Assets/guy-0.jpg'  },
          { id: 3,
            name: 'Moses Eromosele',
             carType:'Toyota Hilux', 
             plateNo: 'AA8E4BKN',
             vehicleType: 'truck',
              timeAway:30, 
              rating:4, 
              img_url:'assets/img/Assets/woody.jpg'  },
                { id: 4,
     name: 'Babatunde Marvel',
      carType:'Toyota Camry', 
      plateNo: 'AA884BKN',
      vehicleType: 'motorcycle',
       timeAway:30, 
       rating:4, 
       img_url:'assets/img/Assets/old-driver-2.jpg'  },
       { id: 5,
        name: 'Akindayo Marvel',
         carType:'Toyota Camry', 
         plateNo: 'BB884BKN',
         vehicleType: 'motorcycle',
          timeAway:30, 
          rating:4, 
          img_url:'assets/img/Assets/old-driver-2.jpg'  },
          { id: 6,
            name: 'Moses Eromosele',
             carType:'Toyota Hilux', 
             plateNo: 'AA8E4BKN',
             vehicleType: 'truck',
              timeAway:30, 
              rating:4, 
              img_url:'assets/img/Assets/old-driver-2.jpg'  },
                { id: 7,
     name: 'Babatunde Marvel',
      carType:'Toyota Camry', 
      plateNo: 'AA884BKN',
      vehicleType: 'car-alt',
       timeAway:30, 
       rating:4, 
       img_url:'assets/img/Assets/black-man.jpg'  },
       { id: 8,
        name: 'Akindayo Marvel',
         carType:'Toyota Camry', 
         plateNo: 'BB884BKN',
         vehicleType: 'motorcycle',
          timeAway:30, 
          rating:4, 
          img_url:'assets/img/Assets/woody.jpg'  },
          { id: 9,
            name: 'Moses Eromosele',
             carType:'Toyota Hilux', 
             plateNo: 'AA8E4BKN',
             vehicleType: 'truck',
              timeAway:30, 
              rating:4, 
              img_url:'assets/img/Assets/old-driver-2.jpg'  },
                { id: 10,
     name: 'Babatunde Marvel',
      carType:'Toyota Camry', 
      plateNo: 'AA884BKN',
      vehicleType: 'car-alt',
       timeAway:30, 
       rating:4, 
       img_url:'assets/img/Assets/black-man.jpg'  },
       { id: 11,
        name: 'Akindayo Marvel',
         carType:'Toyota Camry', 
         plateNo: 'BB884BKN',
         vehicleType: 'motorcycle',
          timeAway:30, 
          rating:4, 
          img_url:'assets/img/Assets/guy-0.jpg'  },
          { id: 12,
            name: 'Moses Eromosele',
             carType:'Toyota Hilux', 
             plateNo: 'AA8E4BKN',
             vehicleType: 'truck',
              timeAway:30, 
              rating:4, 
              img_url:'assets/img/Assets/old-driver-2.jpg'  }
];